spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/cleanApp
      username: postgres
      password: admin
  jpa:
    generate-ddl: true
    show-sql: true
    properties: 
      hibernate:
        format_sql: true
other:
  uploadDir: 