spring:
  datasource:
      url: jdbc:postgresql://localhost:5552/cleanApp
      username: postgres
      password: Ffijvd5555
  jpa:
    generate-ddl: true
    show-sql: true
    properties: 
      hibernate:
        format_sql: true
other:
  uploadDir: 